ln -sf ../../run/LANDUSE.TBL ./
ln -sf ../../run/CLM_* ./
ln -sf ../../run/ozone* ./
ln -sf ../../run/RRTM* ./
ln -sf ../../run/VEGPARM.TBL ./
ln -sf ../../run/SOILPARM.TBL ./
ln -sf ../../run/*TBL ./
ln -sf ../../run/p3_lookup_table_* ./
ln -sf ../../main/*exe ./
